import { describe, expect, it } from "vitest";

import { buildHtmlReport } from "../src/services/reporting/html-report-generator.js";
import { createSampleReportData } from "../fixtures/sample-report-data.js";

describe("buildHtmlReport", () => {
  it("produces a single well-formed self-contained HTML document", () => {
    const html = buildHtmlReport(createSampleReportData());
    expect(html.startsWith("<!doctype html>")).toBe(true);
    expect(html.split("<html").length - 1).toBe(1);
    expect(html.split("</html>").length - 1).toBe(1);
    expect(html.split("<head>").length - 1).toBe(1);
    expect(html.split("<body>").length - 1).toBe(1);
    expect(html).toContain("</body>");
  });

  it("never references a remote origin for a script, stylesheet, or import", () => {
    const html = buildHtmlReport(createSampleReportData());
    expect(html).not.toMatch(/<link[^>]+href=["']https?:\/\//i);
    expect(html).not.toMatch(/<link[^>]+href=["']\/\/[^"']/i);
    expect(html).not.toMatch(/<script[^>]+src=/i);
    expect(html).not.toMatch(/@import\s+url\(["']?https?:\/\//i);
    // the target base URL is legitimate report data, not a resource reference
    expect(html).toContain("https://staging.checkout.example.com");
  });

  it("contains all eight report sections (A-H)", () => {
    const html = buildHtmlReport(createSampleReportData());
    expect(html).toContain('id="section-header"');
    expect(html).toContain("Executive Summary");
    expect(html).toContain("Workflow Timeline");
    expect(html).toContain("Charts");
    expect(html).toContain("Test Case Detail");
    expect(html).toContain("Findings");
    expect(html).toContain("Governance");
    expect(html).toContain('id="section-footer"');
    expect(html).toContain("Generated by Nova");
  });

  it("colors a passed case green and a failed case red, using text labels too", () => {
    const html = buildHtmlReport(createSampleReportData());
    expect(html).toContain('id="case-case-passed"');
    expect(html).toContain('id="case-case-failed"');
    const passedCardStart = html.indexOf('id="case-case-passed"');
    const passedCardSlice = html.slice(passedCardStart, passedCardStart + 400);
    expect(passedCardSlice).toContain("badge-passed");
    expect(passedCardSlice).toContain("Passed");

    const failedCardStart = html.indexOf('id="case-case-failed"');
    const failedCardSlice = html.slice(failedCardStart, failedCardStart + 400);
    expect(failedCardSlice).toContain("badge-failed");
    expect(failedCardSlice).toContain("Failed");
  });

  it("never colors a blocked case's badge green or red", () => {
    const html = buildHtmlReport(createSampleReportData());
    const blockedCardStart = html.indexOf('id="case-case-blocked"');
    expect(blockedCardStart).toBeGreaterThan(-1);
    const blockedCardSlice = html.slice(blockedCardStart, blockedCardStart + 400);
    expect(blockedCardSlice).toContain("badge-blocked");
    expect(blockedCardSlice).not.toContain("badge-passed");
    expect(blockedCardSlice).not.toContain("badge-failed");
  });

  it("renders the exhausted recovery attempt for the recovery-exhausted case", () => {
    const html = buildHtmlReport(createSampleReportData());
    expect(html).toContain("recovery-outcome-exhausted");
    expect(html).toContain("attempt 2 of 3");
  });

  it("renders a trend chart when charts.trend is present, and the fallback text when absent", () => {
    const withTrend = buildHtmlReport(createSampleReportData());
    expect(withTrend).not.toContain("No historical comparison available.");

    const base = createSampleReportData();
    const withoutTrend = buildHtmlReport({
      ...base,
      charts: { ...base.charts, trend: undefined },
    });
    expect(withoutTrend).toContain("No historical comparison available.");
  });

  it("shows 'Not yet signed' when footer.integrityHash is absent", () => {
    const base = createSampleReportData();
    const html = buildHtmlReport(base);
    expect(base.footer.integrityHash).toBeUndefined();
    expect(html).toContain("Not yet signed");
  });

  it("shows the integrity hash value when footer.integrityHash is present", () => {
    const base = createSampleReportData();
    const html = buildHtmlReport({
      ...base,
      footer: { ...base.footer, integrityHash: "sha256:deadbeef" },
    });
    expect(html).toContain("sha256:deadbeef");
    expect(html).not.toContain("Not yet signed");
  });

  it("renders a sticky section nav with a jump link to every content section", () => {
    const html = buildHtmlReport(createSampleReportData());
    expect(html).toContain('class="report-nav"');
    for (const href of [
      "#section-executive-summary",
      "#section-timeline",
      "#section-charts",
      "#section-test-cases",
      "#section-findings",
      "#section-governance",
    ]) {
      expect(html).toContain(`href="${href}"`);
    }
    // the sample data has 2 findings — the nav should surface the count
    expect(html).toContain("Findings (2)");
  });

  it("shows a computed pass rate in the executive summary, and omits it when there are no tests", () => {
    const base = createSampleReportData();
    const html = buildHtmlReport(base);
    // sample data: 1 passed out of 6 total tests
    expect(base.executiveSummary.passed).toBe(1);
    expect(base.executiveSummary.totalTests).toBe(6);
    expect(html).toContain('<div class="value">17%</div><div class="label">Pass rate</div>');

    const empty = buildHtmlReport({
      ...base,
      executiveSummary: { ...base.executiveSummary, totalTests: 0, passed: 0 },
    });
    expect(empty).not.toContain("Pass rate");
  });

  it("cross-links a failed test case to its finding, and the finding back to the test case", () => {
    const html = buildHtmlReport(createSampleReportData());
    const caseStart = html.indexOf('id="case-case-failed"');
    const caseSlice = html.slice(caseStart, caseStart + 800);
    expect(caseSlice).toContain('href="#finding-case-failed-0"');

    const findingStart = html.indexOf('id="finding-case-failed-0"');
    expect(findingStart).toBeGreaterThan(-1);
    const findingSlice = html.slice(findingStart, findingStart + 400);
    expect(findingSlice).toContain('href="#case-case-failed"');
  });

  it("assigns unique anchor ids when a test case has more than one finding", () => {
    const base = createSampleReportData();
    const [firstFinding] = base.findings;
    const html = buildHtmlReport({
      ...base,
      findings: [firstFinding, { ...firstFinding, title: "A second defect on the same case" }],
    });
    expect(html).toContain('id="finding-case-failed-0"');
    expect(html).toContain('id="finding-case-failed-1"');
    expect(html).toContain('href="#finding-case-failed-0"');
    expect(html).toContain('href="#finding-case-failed-1"');
  });
});
